//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCMDEFEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCMDEFEditor.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string closeFileButton {
            get {
                return ResourceManager.GetString("closeFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть Файл (Ctrl+W).
        /// </summary>
        internal static string closeFileButtonToolTip {
            get {
                return ResourceManager.GetString("closeFileButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В файле списков команд в разделе &quot;.
        /// </summary>
        internal static string cmdFileCommentString1 {
            get {
                return ResourceManager.GetString("cmdFileCommentString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раздела &quot;.
        /// </summary>
        internal static string cmdFileErrorBeginSectionXInEnd1 {
            get {
                return ResourceManager.GetString("cmdFileErrorBeginSectionXInEnd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; находится в конце файла..
        /// </summary>
        internal static string cmdFileErrorBeginSectionXInEnd2 {
            get {
                return ResourceManager.GetString("cmdFileErrorBeginSectionXInEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В файле списков команд не удалось найти раздел &quot;.
        /// </summary>
        internal static string cmdFileSectionXNotFound {
            get {
                return ResourceManager.GetString("cmdFileSectionXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл списков команд создан неправильно..
        /// </summary>
        internal static string cmdIncorrectFile {
            get {
                return ResourceManager.GetString("cmdIncorrectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программу невозможно запустить так-как файл списков команд создан неправильно. Вы можете исправить ошибки в файле и снова запустить программу!.
        /// </summary>
        internal static string cmdIncorrectFileInfo {
            get {
                return ResourceManager.GetString("cmdIncorrectFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание выбранной команды.
        /// </summary>
        internal static string commandDescriptionLabel {
            get {
                return ResourceManager.GetString("commandDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные команды.
        /// </summary>
        internal static string commandsListLabel {
            get {
                return ResourceManager.GetString("commandsListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В файле в разделе &quot;.
        /// </summary>
        internal static string commentString1 {
            get {
                return ResourceManager.GetString("commentString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; обнаружен комментарий - &quot;.
        /// </summary>
        internal static string commentString2 {
            get {
                return ResourceManager.GetString("commentString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа пропустит эту строку!.
        /// </summary>
        internal static string commentString3 {
            get {
                return ResourceManager.GetString("commentString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раздела &quot;Section Function Definition&quot; находится в конце файла..
        /// </summary>
        internal static string errorBeginSectionInEndFileSectionFunctionDefinition {
            get {
                return ResourceManager.GetString("errorBeginSectionInEndFileSectionFunctionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раздела &quot;Section General&quot; находится в конце файла..
        /// </summary>
        internal static string errorBeginSectionInEndFileSectionGeneral {
            get {
                return ResourceManager.GetString("errorBeginSectionInEndFileSectionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раздела &quot;Section Misc Function Definition&quot; находится в конце файла..
        /// </summary>
        internal static string errorBeginSectionInEndFileSectionMiscFunctionDefinition {
            get {
                return ResourceManager.GetString("errorBeginSectionInEndFileSectionMiscFunctionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раздела &quot;Section Others&quot; находится в конце файла..
        /// </summary>
        internal static string errorBeginSectionInEndFileSectionOthers {
            get {
                return ResourceManager.GetString("errorBeginSectionInEndFileSectionOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раздела &quot;Section Word Definition&quot; находится в конце файла..
        /// </summary>
        internal static string errorBeginSectionInEndFileSectionWordDefinition {
            get {
                return ResourceManager.GetString("errorBeginSectionInEndFileSectionWordDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало раздела &quot;Section Word Replacement&quot; находится в конце файла..
        /// </summary>
        internal static string errorBeginSectionInEndFileSectionWordReplacement {
            get {
                return ResourceManager.GetString("errorBeginSectionInEndFileSectionWordReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти &quot;end section&quot;..
        /// </summary>
        internal static string errorEndSectionNotFound {
            get {
                return ResourceManager.GetString("errorEndSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутри раздела &quot;.
        /// </summary>
        internal static string errorFileString {
            get {
                return ResourceManager.GetString("errorFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; обнаружен раздел &quot;Section Function Definition&quot;..
        /// </summary>
        internal static string errorFileStringSectionFunctionDefinition {
            get {
                return ResourceManager.GetString("errorFileStringSectionFunctionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; обнаружен раздел &quot;Section General&quot;..
        /// </summary>
        internal static string errorFileStringSectionGeneral {
            get {
                return ResourceManager.GetString("errorFileStringSectionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; обнаружен раздел &quot;Section Misc Function Definition&quot;..
        /// </summary>
        internal static string errorFileStringSectionMiscFunctionDefinition {
            get {
                return ResourceManager.GetString("errorFileStringSectionMiscFunctionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; обнаружен раздел &quot;Section Others&quot;..
        /// </summary>
        internal static string errorFileStringSectionOthers {
            get {
                return ResourceManager.GetString("errorFileStringSectionOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; обнаружен раздел &quot;Section Word Definition&quot;..
        /// </summary>
        internal static string errorFileStringSectionWordDefinition {
            get {
                return ResourceManager.GetString("errorFileStringSectionWordDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; обнаружен раздел &quot;Section Word Replacement&quot;..
        /// </summary>
        internal static string errorFileStringSectionWordReplacement {
            get {
                return ResourceManager.GetString("errorFileStringSectionWordReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string errorHeader {
            get {
                return ResourceManager.GetString("errorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string filePanel {
            get {
                return ResourceManager.GetString("filePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл создан неправильно..
        /// </summary>
        internal static string IncorrentFile {
            get {
                return ResourceManager.GetString("IncorrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string infoHeader {
            get {
                return ResourceManager.GetString("infoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставка.
        /// </summary>
        internal static string insertRibbonTab {
            get {
                return ResourceManager.GetString("insertRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставка (Alt+2).
        /// </summary>
        internal static string insertRibbonTabToolTip {
            get {
                return ResourceManager.GetString("insertRibbonTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string mainRibbonTab {
            get {
                return ResourceManager.GetString("mainRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная (Alt+1).
        /// </summary>
        internal static string mainRibbonTabToolTip {
            get {
                return ResourceManager.GetString("mainRibbonTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        internal static string newFileButton {
            get {
                return ResourceManager.GetString("newFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый Файл (Ctrl+N).
        /// </summary>
        internal static string newFileButtonToolTip {
            get {
                return ResourceManager.GetString("newFileButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string openFileButton {
            get {
                return ResourceManager.GetString("openFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть Файл (Ctrl+O).
        /// </summary>
        internal static string openFileButtonToolTip {
            get {
                return ResourceManager.GetString("openFileButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение невозможно!.
        /// </summary>
        internal static string readingIsImpossible {
            get {
                return ResourceManager.GetString("readingIsImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        internal static string saveAsFileButton {
            get {
                return ResourceManager.GetString("saveAsFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как (Ctrl+Shift+S).
        /// </summary>
        internal static string saveAsFileButtonToolTip {
            get {
                return ResourceManager.GetString("saveAsFileButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string saveFileButton {
            get {
                return ResourceManager.GetString("saveFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить Файл (Ctrl+S).
        /// </summary>
        internal static string saveFileButtonToolTip {
            get {
                return ResourceManager.GetString("saveFileButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить файл - .
        /// </summary>
        internal static string saveFileText {
            get {
                return ResourceManager.GetString("saveFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить текущий файл?.
        /// </summary>
        internal static string saveFileTitle {
            get {
                return ResourceManager.GetString("saveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск (Ctrl+F).
        /// </summary>
        internal static string searchPanel {
            get {
                return ResourceManager.GetString("searchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string searchTextBoxText {
            get {
                return ResourceManager.GetString("searchTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном файле не удалось найти раздел &quot;Section Function Definition&quot;!.
        /// </summary>
        internal static string sectionFunctionDefinitionNotFound {
            get {
                return ResourceManager.GetString("sectionFunctionDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном файле не удалось найти раздел &quot;Section General&quot;!.
        /// </summary>
        internal static string sectionGeneralNotFound {
            get {
                return ResourceManager.GetString("sectionGeneralNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном файле не удалось найти раздел &quot;Section Misc Function Definition&quot;!.
        /// </summary>
        internal static string sectionMiscFunctionDefinitionNotFound {
            get {
                return ResourceManager.GetString("sectionMiscFunctionDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном файле не удалось найти раздел &quot;Section Others&quot;!.
        /// </summary>
        internal static string sectionOthersNotFound {
            get {
                return ResourceManager.GetString("sectionOthersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном файле не удалось найти раздел &quot;Section Word Definition&quot;!.
        /// </summary>
        internal static string sectionWordDefinitionNotFound {
            get {
                return ResourceManager.GetString("sectionWordDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данном файле не удалось найти раздел &quot;Section Word Replacement&quot;!.
        /// </summary>
        internal static string sectionWordReplacementNotFound {
            get {
                return ResourceManager.GetString("sectionWordReplacementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string settingsButton {
            get {
                return ResourceManager.GetString("settingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string settingsButtonToolTip {
            get {
                return ResourceManager.GetString("settingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык интерфейса помеяется после перезагрузки программы..
        /// </summary>
        internal static string settingsUSLanguageInfo {
            get {
                return ResourceManager.GetString("settingsUSLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string settingsUSLanguageLabel {
            get {
                return ResourceManager.GetString("settingsUSLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформление.
        /// </summary>
        internal static string treeViewCustomize {
            get {
                return ResourceManager.GetString("treeViewCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string treeViewLanguage {
            get {
                return ResourceManager.GetString("treeViewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор языка.
        /// </summary>
        internal static string treeViewSelectLanguage {
            get {
                return ResourceManager.GetString("treeViewSelectLanguage", resourceCulture);
            }
        }
    }
}
